--- #YAML:1.0
name:                Statistics-Gtest
version:             0.07
abstract:            calculate G-statistic for tabular data
license:             ~
author:              
    - David Fleck <david.fleck@mchsi.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
